### ISSUE TITLE
npm startできない

### ISSUE THREAD

**Issue by yumetodo** [asciidwango/js-primer#147]
自分だけなのかもしれませんが、npm startできなかったので報告だけしておきます。

```sh
$ npm start

> js-primer@1.0.0 start /home/yumetodo/js-primer
> gitbook serve

Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 12 plugins are installed 
info: loading plugin "include-codeblock"... OK 
info: loading plugin "edit-link"... OK 
info: loading plugin "canonical-link"... OK 
info: loading plugin "ga"... OK 
info: loading plugin "js-console"... OK 
info: loading plugin "livereload"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 19 pages 
info: found 83 asset files 
warn: "options" property is deprecated, use config.get(key) instead 
info: >> generation finished with success in 5.1s ! 

Starting server ...
Serving book on http://localhost:4000

Error: watch /home/yumetodo/js-primer/node_modules/core-js/library/es5 ENOSPC

npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/home/yumetodo/.nvm/versions/node/v6.7.0/bin/node" "/home/yumetodo/.nvm/versions/node/v6.7.0/bin/npm" "start"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! js-primer@1.0.0 start: `gitbook serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the js-primer@1.0.0 start script 'gitbook serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the js-primer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gitbook serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs js-primer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls js-primer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yumetodo/js-primer/npm-debug.log
```

``npm-debug.log``

```sh
0 info it worked if it ends with ok
1 verbose cli [ '/home/yumetodo/.nvm/versions/node/v6.7.0/bin/node',
1 verbose cli   '/home/yumetodo/.nvm/versions/node/v6.7.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.7.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle js-primer@1.0.0~prestart: js-primer@1.0.0
6 silly lifecycle js-primer@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle js-primer@1.0.0~start: js-primer@1.0.0
8 verbose lifecycle js-primer@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle js-primer@1.0.0~start: PATH: /home/yumetodo/.nvm/versions/node/v6.7.0/lib/node_modules/npm/bin/node-gyp-bin:/home/yumetodo/js-primer/node_modules/.bin:/home/yumetodo/.nvm/versions/node/v6.7.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle js-primer@1.0.0~start: CWD: /home/yumetodo/js-primer
11 silly lifecycle js-primer@1.0.0~start: Args: [ '-c', 'gitbook serve' ]
12 silly lifecycle js-primer@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle js-primer@1.0.0~start: Failed to exec start script
14 verbose stack Error: js-primer@1.0.0 start: `gitbook serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/yumetodo/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/yumetodo/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid js-primer@1.0.0
16 verbose cwd /home/yumetodo/js-primer
17 error Linux 4.4.0-36-generic
18 error argv "/home/yumetodo/.nvm/versions/node/v6.7.0/bin/node" "/home/yumetodo/.nvm/versions/node/v6.7.0/bin/npm" "start"
19 error node v6.7.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error js-primer@1.0.0 start: `gitbook serve`
22 error Exit status 1
23 error Failed at the js-primer@1.0.0 start script 'gitbook serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the js-primer package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gitbook serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs js-primer
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls js-primer
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

```
$ npm gitbook --version
3.10.8
$ nvm current
v6.7.0
$ uname -a
Linux yumetodo-desktop 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by azu** [comment]
おそらく `npm run build` (ビルドのみ)は動いてる感じですかね?
watchのみだめなら、ファイルを監視するディスクリプタの許容数を超えているのが原因なように見えます。
Linuxでやってないのではっきりはわからないですが、上限数を上げると大丈夫かもしれません。

- https://github.com/gruntjs/grunt-contrib-watch/issues/236
- http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc
- [ファイルディスクリプタとかulimitとか/proc/sys/fsとかめも - tweeeetyのぶろぐ的めも](http://tweeeety.hateblo.jp/entry/20131220/1387508776 "ファイルディスクリプタとかulimitとか/proc/sys/fsとかめも - tweeeetyのぶろぐ的めも")

**Comment by yumetodo** [comment]
なるほどそういうことか。StackOverflowでの回答にある``echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p``で解決しました。
