### ISSUE TITLE
ローカル環境での `npm test` がエラーになります

### ISSUE THREAD

**Issue by kangetsu121** [asciidwango/js-primer#1476]
## 事象

ローカル環境で `npm test` 実行時に `ReferenceError: document is not defined` でテストが失敗する

## 環境情報

```console
kangetsu@ubuntu20:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
kangetsu@ubuntu20:~$
```

```console
kangetsu@ubuntu20:~/work/js-primer$ node -v
v16.17.0
kangetsu@ubuntu20:~/work/js-primer$ npm -v
8.15.0
kangetsu@ubuntu20:~/work/js-primer$
```

## ログなど

```console
kangetsu@ubuntu20:~/work/js-primer$ npm install && npm test
[...]
[test:example         ]   961 passing (12s)
[test:example         ]   1 failing
[test:example         ] 
[test:example         ]   1) example:es
[test:example         ]        example:es /use-case/nodecli/node_modules/object-inspect/example/inspect.js:
[test:example         ]      ReferenceError: document is not defined
[test:example         ]       at Object.<anonymous> (source/use-case/nodecli/node_modules/object-inspect/example/inspect.js:6:9)
[test:example         ]       at Module._compile (node:internal/modules/cjs/loader:1126:14)
[test:example         ]       at Module._compile (node_modules/pirates/lib/index.js:136:24)
[test:example         ]       at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
[test:example         ]       at Object.newLoader [as .js] (node_modules/pirates/lib/index.js:141:7)
[test:example         ]       at Module.load (node:internal/modules/cjs/loader:1004:32)
[test:example         ]       at Function.Module._load (node:internal/modules/cjs/loader:839:12)
[test:example         ]       at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
[test:example         ]       at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
[test:example         ]       at async Promise.all (index 0)
[test:example         ]       at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
[test:example         ] 
[test:example         ] 
[test:example         ] 
ERROR: "test:example" exited with 1.
kangetsu@ubuntu20:~/work/js-primer$
```

```
kangetsu@ubuntu20:~/work/js-primer$ ls source/use-case/nodecli/node_modules/object-inspect/example/inspect.js 
source/use-case/nodecli/node_modules/object-inspect/example/inspect.js
```

- `source/use-case/nodecli/node_modules/object-inspect/example/inspect.js`

    ```js:inspect.js
    'use strict';

    /* eslint-env browser */
    var inspect = require('../');

    var d = document.createElement('div');
    d.setAttribute('id', 'beep');
    d.innerHTML = '<b>wooo</b><i>iiiii</i>';

    console.log(inspect([d, { a: 3, b: 4, c: [5, 6, [7, [8, [9]]]] }]));
    ```

## 背景の推測

#1465 における `example-es-test.js` の更新で glob を使ってテスト対象を指定していますが、これにより `source/use-case/nodecli/node_modules/object-inspect/example/inspect.js` がパターンにマッチしてテスト対象となり、そこで Node.js 環境で `document` オブジェクトを参照してしまい `ReferenceError: document is not defined` エラーでテストが落ちているように見えます。
https://github.com/asciidwango/js-primer/blob/363229a270314c3d9300583880a723c66cdaeb23/test/example-es-test.js#L17

CI で発生しない理由はわかりませんが、ローカルでは `npm ci` 実行後に `npm test` なども試しましたが同様にエラーとなりました。

意図的なものであったり、何か手順など勘違いしていたら申し訳ありませんが、ご確認よろしくお願いします。

**Comment by azu** [comment]
https://github.com/asciidwango/js-primer/blob/363229a270314c3d9300583880a723c66cdaeb23/test/example-es-test.js#L14-L18
に`!${sourceDir}/**/node_modules{,/**}`,` を足すのが良さそうですね。

参考 https://github.com/asciidwango/js-primer/blob/363229a270314c3d9300583880a723c66cdaeb23/test/example-doc-test.js#L26
